# Generated by Django 3.0.4 on 2020-05-05 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karthiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='karthidata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
